// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhV1rWDNspbfpjuIjOy-J1_OcsFu0RnIw',
    appId: '1:874918817614:web:b775a4b77a9522ea1cb81f',
    messagingSenderId: '874918817614',
    projectId: 'stok-barang-edad1',
    authDomain: 'stok-barang-edad1.firebaseapp.com',
    databaseURL: 'https://stok-barang-edad1-default-rtdb.firebaseio.com',
    storageBucket: 'stok-barang-edad1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrNfrV7AGWohDSRsjlQmKNxgUYPj8AH60',
    appId: '1:874918817614:android:403930162ad0904c1cb81f',
    messagingSenderId: '874918817614',
    projectId: 'stok-barang-edad1',
    databaseURL: 'https://stok-barang-edad1-default-rtdb.firebaseio.com',
    storageBucket: 'stok-barang-edad1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1agod0SLbdNlJW0QLNltPj_PgCPpUas4',
    appId: '1:874918817614:ios:29de38af1f34f10c1cb81f',
    messagingSenderId: '874918817614',
    projectId: 'stok-barang-edad1',
    databaseURL: 'https://stok-barang-edad1-default-rtdb.firebaseio.com',
    storageBucket: 'stok-barang-edad1.appspot.com',
    iosClientId: '874918817614-ttv1boq1vgbeiaolpdmg03nnrujncnvb.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteCashId',
  );

}